- name: Create temp directory
  tempfile:
    state: directory
    path: /tmp
  register: temp_path
- set_fact:
    temp_path: "{{ temp_path.path }}"

- name: Create terraform file
  shell: python {{ py_path }}/create_softlayer-vm-tf.py {{ temp_path }} {{ tf_tempfile }} {{ softlayer_api_key }} {{ softlayer_username }} {{ count }} {{ key_name }} "{{ public_key }}" {{ hostname }} {{ domain }} {{ os_reference_code }} {{ datacenter }} {{ network_speed }} {{ hourly_billing }} {{ local_disk }} {{ private_network_only }} {{ cores }} {{ memory }} {{ disks }} {{ public_vlan_id }} {{ private_vlan_id }}
  register: result
- debug:
    var: result.stdout   

- name: Run terraform init
  shell: terraform init 
  args:
    chdir: "{{ temp_path }}"
  register: result
- debug:
    var: result.stdout

- name: Run terraform template
  terraform:
    binary_path: /usr/local/bin/terraform
    force_init: yes
    project_path: "{{ temp_path }}"
    state: present
  register: result
- debug:
    var: result.stdout

- name: Add inventories from created VM in Softlayer
  shell: python {{ py_path }}/run_inventory_script.py {{ userid }} {{ password }} {{ zcomposer_url }} {{ inventory_name }}
  register: result
- debug:
    var: result.stdout        

- name: Delete temp directory
  file:
    state: absent
    path: "{{ temp_path }}"
  register: result
- debug:
    var: result.stdout 

